stages:
  - test

test:
  stage: test
  image: node
  script:
    - echo "Testing App"
    - cd apps/api
    - yarn install
    - yarn db:start
    - yarn db:migrate
    - yarn build
    - CI=true yarn test
    - echo "Test successfully!"
